vox_nav_planner_server_rclcpp_node:
  ros__parameters:
    planner_plugin: "SE3Planner"          # other options: "SE2Planner", "ElevationPlanner", "OptimalElevationPlanner"
    expected_planner_frequency: 1.0
    planner_name: "RRTstar"                            
    planner_timeout: 2.0
    interpolation_parameter: 20                         # set to 0 if you wanna disable interpolating and smooting, otherwise 25 is a good default value                    
    octomap_voxel_size: 0.4
    robot_body_dimens:
      x: 0.2
      y: 0.2
      z: 0.4
    robot_mesh_path: ""
    SE3Planner:
      # Available Planners Include: PRMstar,LazyPRMstar,RRTstar,RRTsharp,RRTXstatic,InformedRRTstar,BITstar, 
                                 #  ABITstar,AITstar,CForest,LBTRRT,SST,TRRT,SPARS,SPARStwo,FMT,AnytimePathShortening
      plugin: "vox_nav_planning::SE3Planner"         # CForest: Reccomended
      state_space_boundries: 
        minx: -100.0
        maxx: 100.0
        miny: -100.0
        maxy: 100.0
        minz: -100.0
        maxz: 100.0

vox_nav_controller_server_rclcpp_node:
   ros__parameters: 
      controller_plugin: "MPCControllerCasadiROS"                               # other options: non
      controller_frequency: 100.0                                              # acado is really fast(+1000.0Hz) casadi can deal up to just 20.0Hz maybe
      goal_tolerance_distance: 0.3                                            # in meters, once smaller than this one controller tries to minimize orientation error
      goal_tolerance_orientation: 0.3                                         # in radians, once smaller than this value,controller exits with success
      transform_timeout: 0.01                                                 # seconds, this is used to regulate lookUpTransfrom calls from tf2
      global_plan_look_ahead_distance: 4.5                                    # look this amount of meters from current robot pose to remaining global path
      ref_traj_se2_space: "REEDS"                                             # "DUBINS","REEDS", "SE2" ### PS. Use DUBINS OR REEDS for Ackermann
      rho: 3.0                                                                # Curve radius form reeds and dubins only
      robot_radius: 1.25                                                             
      MPCControllerCasadiROS:
         plugin: "mpc_controller_casadi::MPCControllerCasadiROS"
         N: 10                                                                # timesteps in MPC Horizon
         DT: 0.2                                                              # discretization time between timesteps(s)
         L_F: 0.67                                                            # distance from CoG to front axle(m)
         L_R: 0.67                                                            # distance from CoG to rear axle(m)
         V_MIN: -0.4                                                          # min / max velocity constraint(m / s)
         V_MAX: 1.0
         A_MIN: -0.1                                                          # min / max acceleration constraint(m / s ^ 2)
         A_MAX: 1.0
         DF_MIN: -0.8                                                         # min / max front steer angle constraint(rad)
         DF_MAX: 0.8
         A_DOT_MIN: -0.5                                                      # min / max jerk constraint(m / s ^ 3)
         A_DOT_MAX: 0.5
         DF_DOT_MIN: -0.5                                                     # min / max front steer angle rate constraint(rad / s)
         DF_DOT_MAX: 0.5
         Q: [10.0, 10.0, 0.1, 0.1]                                            # weights on x, y, psi, v.
         R: [10.0, 100.0]                                                     # weights on jerk and slew rate(steering angle derivative)
         debug_mode: False                                                    # enable/disable debug messages
         params_configured: True
         obstacle_cost: 50.0
         max_obstacles: 4

      plan_refiner_plugin: "TraversabilityBasedPlanRefiner"
      plan_refiner_frequency: 5.5
      TraversabilityBasedPlanRefiner:
        plugin: "vox_nav_control::TraversabilityBasedPlanRefiner"
        local_goal_max_nn_dist: 10.0
        supervoxel_disable_transform: false
        supervoxel_resolution: 0.1
        supervoxel_seed_resolution: 0.2
        supervoxel_color_importance: 0.0
        supervoxel_spatial_importance: 1.0
        supervoxel_normal_importance: 0.0
        supervoxel_dist: 0.0
        supervoxel_cost: 1.0

vox_nav_map_server_rclcpp_node:
  ros__parameters:
    pcd_map_filename: /home/atas/ros2_ws/src/VOX_NAV_FRIENDS/vox_nav/vox_nav_bringup/maps/empty.pcd # Provide a PCD format map

