pcl2octomap_converter_rclcpp_node:
  ros__parameters:
    input_pcd_filename: /home/atas/pointnet2_pytorch/data/decomposed_traversability_cloud.pcd
    output_binary_octomap_filename: /home/atas/pointnet2_pytorch/data/decomposed_traversability_cloud.ot
    octomap_voxelsize: 0.2
    cloud_transform:
      translation:
        x: 0.0
        y: 0.0
        z: 0.0 #1.0
      rotation: #intrinsic rotation X-Y-Z (r-p-y)sequence
        r: 0.0 #3.14
        p: 0.0 #1.57
        y: 0.0 #1.57
    apply_filters: False    
    downsample_voxel_size: 0.1
    remove_outlier_mean_K: 50
    remove_outlier_stddev_threshold: 0.1
    remove_outlier_radius_search: 0.1
    remove_outlier_min_neighbors_in_radius: 1
